* Best Anemia Predictor Competition
** Introduction

In this exercise, you will use the principles of data pre-processing, data mining, and machine learning to create a supervised machine learning classifier. The classifier will predict future anemia based on a patient's last available CBC. This is a competition, and the best performing classifiers will win prizes!

** Learning Objectives

** Data Acquisition and Pre-processing

Data will be made available when the competition is released. 

The dataset you will be working with is de-identifed CBC and differential results from our LIS database. All of these CBC results have normal hemoglobin and hematocrit, but half of the patients will be anemic on their next CBC. The subsequent, anemic CBC is not shown, but these patients are identified in the subs-anemia column with the value "Yes". The other half of the included CBC results are from patients who were not anemic on their next CBC (subs-anemia = "No"). 

Your job is to use the available CBC data to predict which patients will become anemic. These results were selected so that the subs-anemia groups have comparable distributions of hematocrit in the first result. Check out the R script to see how these data were generated and de-identified.

** Pre-processing and Data Mining

The first step will be data pre-processing and data mining to understand the dataset. You will need to make decisions about which data to include, exclude, and modify, before applying machine learning techniques. For example, some CBCs in the dataset do not have complete differential results. You will decide whether to keep or exclude this data from analysis (or possibly even impute the missing values). You will decide whether the scale of each column of data is appropriate or should be changed (e.g. normalized) before analysis. This work can be done in any program you choose, such as Excel. Refer back to the data pre-processing and data mining lecture for help. 

** Supervised Machine Learning Classifier

The actual machine learning will be do in a program called [[https://www.cs.waikato.ac.nz/ml/weka/][Weka]]. Weka is a powerful but easy to use machine learning platform with a graphical, point-and-click interface. 

*** Install Weka and Import Data

[[https://www.cs.waikato.ac.nz/ml/weka/downloading.html][Download]] a stable version of Weka for your operating system, and follow the installation instructions from the website. To import the CBC data that you have pre-processed, save that data as a comma-separated value (.csv) file. You can save as csv in Excel. Be sure the top of the spreadsheet contains only a single row of column labels, then only data beneath (see LINKexample). Now in the initial Weka window (Weka GUI Chooser), select ArffViewer the Tools menu. Open your csv in the ArffViewer. In the ArffViewer, you can modify the rows and columns of your data by right-clicking on them. The only important change to make is to identify an attribute as class- the column which describes the outcome you are trying to predict. Our classification attribute is subs-anemia. Right-click the column header for subs-anemia and select Attribute as Class. Now save as an .arff file type. Back at the 


  - Machine Learning
    - Getting Started with Weka
      - Install
      - Import
      - Analyze
      - Classify
- some CBC results on my desktop smb://surgpath.wupath.wucon.wustl.edu/Residents-Fellows/jszymanski/Desktop/3.2 to 3.12.csv
- Ron picks prize
- bin distributions to match
- Aspects of exercise in scope
  - Weka functionality
  - Principles of data cleaning to ML
    - Normalization
  - Principles of supervised ML classification problem for
    - Non-med example
    - 
- Out of scope
  - Detail about CBCs
  - Detail about dataset
  - Detail about each ML algorithm
- CBC w/ diff
  - predict a low future count- i.e. platelet 
- Good demo sites
  - [[https://machinelearningmastery.com/load-csv-machine-learning-data-weka/][How To Load CSV Machine Learning Data in Weka]]
  - [[https://machinelearningmastery.com/how-to-run-your-first-classifier-in-weka/][How to Run Your First Classifier in Weka]]
  - [[http://machinelearningmastery.com/binary-classification-tutorial-weka/][How To Work Through a Binary Classification Project in Weka Step-By-Step]]

Refer back to Dr. Jackups ML lecture for help. 
